env:
  "googleappsscript/googleappsscript": true
parserOptions:
  ecmaVersion: 5
plugins: ["googleappsscript"]
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always